# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'tsar6'
        repository: 'caesar269 / adservice'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: latest
    
    - task: Docker@2
      inputs:
        containerRegistry: 'tsar6'
        repository: 'caesar269 / adservice'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/src/frontend/**/Dockerfile'
        tags: latest
