# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ACR'
        repository: 'tsar6'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/src/adservice/**/Dockerfile'
        tags: 'latest'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'ACR'
        repository: 'tsar6'
        command: 'buildAndPush'
        Dockerfile: '''$(Build.SourcesDirectory)/src/cartservice/src/**/Dockerfile'
        tags: 'latest'
    
